import { Html, Head, Main, NextScript } from 'next/document';

export default function Document() {
	return (
		<Html lang='en'>
			<Head>
				<link
					rel='stylesheet'
					as='style'
					href='https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable.min.css'
				/>
				<title>calorie-mate</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				{/* <meta name='appleid-signin-client-id' content='[CLIENT_ID]' />
				<meta name='appleid-signin-scope' content='[SCOPES]' />
				<meta name='appleid-signin-redirect-uri' content='[REDIRECT_URI]' />
				<meta name='appleid-signin-state' content='[STATE]' />
				<meta name='appleid-signin-nonce' content='[NONCE]' />
				<meta name='appleid-signin-use-popup' content='true' />
				<script
					type='text/javascript'
					src='https://appleid.cdn-apple.com/appleauth/static/jsapi/appleid/1/en_US/appleid.auth.js'
				/> */}
			</Head>
			<body>
				{/* <script
					type='text/javascript'
					src='https://appleid.cdn-apple.com/appleauth/static/jsapi/appleid/1/en_US/appleid.auth.js'
				></script> */}
				{/* <div
					id='appleid-signin'
					data-color='black'
					data-border='true'
					data-type='sign in'
				></div> */}
				<script type='text/javascript'>
					{/* {AppleID.auth.init({
						clientId: '[CLIENT_ID]',
						scope: '[SCOPES]',
						redirectURI: '[REDIRECT_URI]',
						state: '[STATE]',
						nonce: '[NONCE]',
						usePopup: true,
					})} */}
				</script>
				<Main />
				<NextScript />
			</body>
		</Html>
	);
}
