#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 마지막 커밋 정보 가져오기
commit_hash=$(git rev-parse HEAD)
commit_msg=$(git log -1 --pretty=%B)
author=$(git log -1 --pretty=format:'%an')
files=$(git diff-tree --no-commit-id --name-only -r HEAD | sed ':a;N;$!ba;s/\n/, /g')

# 현재 브랜치 이름 가져오기
branch=$(git rev-parse --abbrev-ref HEAD)

# 디스코드 웹훅 URL (실제 URL로 변경해야 함)
webhook_url="https://discord.com/api/webhooks/1275371120203141223/SwN1ZforfVZthV76k7ihUOxA_S63WVmhgwIVrbi6hkCUAnq-UpuDXYhrRiHzJjzZ8e4a"

# 디스코드 메시지 생성
read -r -d '' payload << EOM
{
  "embeds": [{
    "title": "새로운 커밋이 푸시되었습니다",
    "color": 5814783,
    "fields": [
      {
        "name": "커밋 해시",
        "value": "$commit_hash"
      },
      {
        "name": "작성자",
        "value": "$author"
      },
      {
        "name": "브랜치",
        "value": "$branch"
      },
      {
        "name": "커밋 메시지",
        "value": "$commit_msg"
      },
      {
        "name": "변경된 파일",
        "value": "$files"
      }
    ]
  }]
}
EOM

# 디스코드 웹훅으로 데이터 전송
curl -H "Content-Type: application/json" -d "$payload" $webhook_url